# Generated by Django 2.1.5 on 2021-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(default='Unknown User', max_length=20),
            preserve_default=False,
        ),
    ]
